version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
      - /home/owner/Documents/mrdouglas.org/instagram_sav_a_dc3_extracted:/data/instagram_sav_a_dc3_extracted:ro
    environment:
      - MEDIA_ROOT=/data/instagram_sav_a_dc3_extracted
      - DB_PATH=/app/db/posts.db
