version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
      - ../frontend/public/media:/app/media:ro
    environment:
      - NODE_ENV=production
      - MEDIA_ROOT=/app/media
